title: Conference Notes
description: Hand-taken notes from tech conferences
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: https://elderanakain.github.io
baseurl: /konf

gh_edit_link: true
gh_edit_link_text: Edit on GitHub
gh_edit_repository: https://github.com/elderanakain/konf
gh_edit_branch: main
gh_edit_view_mode: tree
